/**
 * Regenerate `migrations/meta/_journal.json` from the on-disk SQL files.
 *
 * WHY THIS EXISTS
 * ---------------
 * `drizzle-kit migrate` (the production migration runner — see
 * packages/db/package.json `migrate:cloud`, .github/workflows/deploy-*.yml)
 * needs `meta/_journal.json` to know which SQL files to apply and in what
 * order. Drizzle normally writes this file as part of `drizzle-kit
 * generate` from a TypeScript schema. Lewis hand-authors raw SQL in
 * `migrations/*.sql` instead, so the journal is generated by this script.
 *
 * Run after every new migration file lands (or before opening the PR that
 * adds one):
 *
 *   pnpm --filter @lewis/db migrate:journal
 *
 * The script is idempotent — re-running it without changes produces a
 * byte-identical journal. CI also enforces this: the file is committed,
 * and any drift between disk and regenerated output fails the build via
 * `migrate:journal:check` (also in package.json).
 *
 * DESIGN NOTES
 * ------------
 * - `when` (ms timestamp) is derived from a stable epoch + idx*minute so
 *   the journal is reproducible. We don't use file mtime: it drifts on
 *   git checkout, IDE saves, and fresh clones, which would make the
 *   committed journal non-deterministic.
 * - `idx` matches the 4-digit filename prefix minus 1 (filenames are
 *   1-indexed `0001..NNNN`; idx is 0-indexed). The script asserts the
 *   filename indices are sequential — no gaps, no dupes.
 * - `tag` is the filename without `.sql`, which is what the drizzle-orm
 *   migrator reads at deploy time.
 * - `breakpoints: true` matches drizzle-kit's default for newly
 *   generated migrations. Our hand-authored files don't contain the
 *   `--> statement-breakpoint` marker, so the value is functionally
 *   irrelevant — but using `true` keeps us compatible with future
 *   drizzle-kit-generated entries if the team ever runs `generate`.
 * - The journal stores `tag` and `when` only; the SHA-256 hash of each
 *   file is computed by drizzle-orm at runtime (migrator.js) and stored
 *   in the `__drizzle_migrations.hash` column. Editing an applied
 *   migration causes a hash mismatch and aborts the next deploy — this
 *   is the safety net we want for HIPAA migration provenance.
 */

import { readdir, mkdir, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

// Anchor migrations dir to this script's location so the resolver is
// cwd-invariant. Running the script via `pnpm --filter @lewis/db
// migrate:journal` (cwd=packages/db) and via `tsx packages/db/scripts/...`
// (cwd=repo root) both resolve to the same migrations folder.
const scriptDir = dirname(fileURLToPath(import.meta.url));

type JournalEntry = {
  idx: number;
  version: "7";
  when: number;
  tag: string;
  breakpoints: true;
};

type Journal = {
  version: "7";
  dialect: "postgresql";
  entries: JournalEntry[];
};

// 2026-01-01T00:00:00Z — chosen because it predates every Lewis migration
// commit and won't collide with any drizzle-kit-generated `when` if the
// team ever uses `drizzle-kit generate` later (drizzle-kit uses Date.now()
// at generation time, which will always be much larger than this).
const STABLE_EPOCH = Date.UTC(2026, 0, 1, 0, 0, 0);
const ENTRY_INTERVAL_MS = 60_000;

const FILENAME_PATTERN = /^(\d{4})_[a-z0-9_]+\.sql$/;

export async function buildJournal(migrationsDir: string): Promise<Journal> {
  const allFiles = await readdir(migrationsDir);
  const sqlFiles = allFiles.filter((f) => f.endsWith(".sql")).sort();

  if (sqlFiles.length === 0) {
    throw new Error(`No .sql files found in ${migrationsDir}`);
  }

  const entries: JournalEntry[] = [];
  const seenIndices = new Set<number>();

  for (let position = 0; position < sqlFiles.length; position++) {
    const file = sqlFiles[position];
    if (file === undefined) continue; // unreachable; satisfies noUncheckedIndexedAccess

    const match = FILENAME_PATTERN.exec(file);
    if (!match) {
      throw new Error(
        `Migration filename '${file}' does not match the expected ` +
          `<NNNN>_<snake_name>.sql pattern. Rename it before regenerating.`,
      );
    }

    // Sequential 1-based check: 0001, 0002, 0003... no gaps, no dupes.
    const filenameIndex = Number.parseInt(match[1] ?? "", 10);
    if (filenameIndex !== position + 1) {
      throw new Error(
        `Migration ordering broken: file '${file}' is at sort position ` +
          `${position + 1} but its filename prefix says ${filenameIndex}. ` +
          `Migrations must be sequential 0001..NNNN with no gaps or duplicates.`,
      );
    }
    if (seenIndices.has(filenameIndex)) {
      throw new Error(`Duplicate migration index ${filenameIndex} in ${file}`);
    }
    seenIndices.add(filenameIndex);

    entries.push({
      idx: position,
      version: "7",
      when: STABLE_EPOCH + position * ENTRY_INTERVAL_MS,
      tag: file.replace(/\.sql$/, ""),
      breakpoints: true,
    });
  }

  return {
    version: "7",
    dialect: "postgresql",
    entries,
  };
}

export function serializeJournal(journal: Journal): string {
  // Two-space indent + trailing newline matches what `drizzle-kit generate`
  // produces, so a future maintainer running generate against this folder
  // gets a no-op diff instead of churn.
  return `${JSON.stringify(journal, null, 2)}\n`;
}

async function main(): Promise<void> {
  const migrationsDir = resolve(scriptDir, "..", "migrations");
  const metaDir = join(migrationsDir, "meta");
  const journalPath = join(metaDir, "_journal.json");

  const journal = await buildJournal(migrationsDir);

  await mkdir(metaDir, { recursive: true });
  await writeFile(journalPath, serializeJournal(journal), "utf8");

  console.warn(`Wrote ${journal.entries.length} entries to ${journalPath}`);
}

// Only run main() when invoked directly (not when imported by tests or
// by check-migration-journal.ts). Strict file-URL equality survives
// `.ts` → `.js` compilation and rejects sibling files with a similar
// suffix; `endsWith` would fail both.
const entryUrl = process.argv[1] ? pathToFileURL(resolve(process.argv[1])).href : undefined;
const invokedDirectly = entryUrl === import.meta.url;
if (invokedDirectly) {
  main().catch((error: unknown) => {
    const message = error instanceof Error ? error.message : "Unknown error";
    console.error(`regenerate-migration-journal failed: ${message}`);
    process.exit(1);
  });
}
